# Generated by Django 4.0.6 on 2022-08-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('division', models.CharField(choices=[('Production division', 'Production Division'), ('Marketing division', 'Marketing Division'), ('General division', 'General Division'), ('Personnel division', 'Personnel Division'), ('Human resource division', 'Human Resource Division'), ('Advertising division', 'Advertising Division')], max_length=255)),
                ('type_topology', models.CharField(choices=[('Bus topology', 'Bus Topology'), ('Star topology', 'Star Topology'), ('Ring topology', 'Ring Topology')], max_length=255)),
            ],
        ),
    ]
